services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy:1.4
        container_name: nginx-proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - certs:/etc/nginx/certs:ro
            - html:/usr/share/nginx/html
        network_mode: bridge
    acme-companion:
        container_name: nginx-proxy-acme
        restart: always
        image: nginxproxy/acme-companion
        volumes_from:
            - nginx-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - certs:/etc/nginx/certs:rw
            - acme:/etc/acme.sh
        # network_mode: bridge
        environment:
            DEFAULT_EMAIL: teddy.dubal+devqueen@gmail.com
        network_mode: bridge
volumes:
    acme:
    conf:
    certs:
    vhost:
    html: