version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/nginx/conf.d
            - /usr/share/nginx/html
            - /etc/nginx/vhost.d
            - ./nginx/certs:/etc/nginx/certs:ro
        networks:
            - front
    dockergen:
        image: jwilder/docker-gen
        container_name: nginx-gen
        command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
            - nginx-volume
        networks:
            - front
    letsencrypt-nginx-proxy-companion:
        restart: always
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt-nginx-proxy-companion
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./nginx/certs:/etc/nginx/certs:rw
            - nginx-volume
        networks:
            - front
        environment:
            - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
volumes:
    nginx-volume:
        - /etc/nginx/conf.d
        - /usr/share/nginx/html
        - /etc/nginx/vhost.d
        - ./nginx/certs:/etc/nginx/certs:ro
networks:
    front: